### PR TITLE
Allow any CC:Tweaked version 1.91.0 and up

### PR DESCRIPTION
**Pull request by Brycey92**

### CODE REVIEW

**Comment by Cookie04DE** [comment]
Just uploaded the new version. Should be available here after approval: https://www.curseforge.com/minecraft/mc-mods/digital-items/files/all

**Comment by Brycey92** [comment]
Thanks!

It's not really related, but do you plan to merge the changes from UpsilonDev's fork?

**Comment by Cookie04DE** [comment]
If I can do so without breaking compatability I might. No promises though, since I am currently very busy with my education. I also thought about making a sequel mod which addresses a bunch of issues and other things I can't do without breaking compatability. So if I have the time and motivation that might happen. Again no promises.

**Comment by Brycey92** [comment]
Entirely fair, I know how busy it can get with school/college! I look forward to the update or sequel, if you make them :smile:

**Pull request merged**
